version: "3"
services:
  ssh:
    image: wrfly/example:ssh
    environment:
      - FLAG=<FLAG>
    ports:
      - 22
    deploy:
      placement:
        constraints:
          - node.role != manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.05' # CPU Limit 5%
          memory: 10M  # Mem Limit 10M
        reservations:
          cpus: '0.001'
          memory: 4M