version: "3"
services:
  nginx:
    image: nginx:latest
    environment:
      - FLAG=<FLAG>
    ports:
      - 80
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.05' # CPU Limit 5%
          memory: 50M  # Mem Limit 50M
        reservations:
          cpus: '0.001'
          memory: 10M
    depends_on:
      - busybox
  busybox:
    image: busybox:latest
    environment:
      - FLAG=<FLAG>
    command: sleep 999
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.05' # CPU Limit 5%
          memory: 50M  # Mem Limit 50M
        reservations:
          cpus: '0.001'
          memory: 10M