version: "3"
services:
  ImageMagick:
    image: wrfly/cve-2016-3714
    environment:
      - FLAG=<FLAG>
    ports:
      - 80
    deploy:
      placement:
        constraints:
          - node.role != manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.05' # CPU Limit
          memory: 30M  # Mem Limit
        reservations:
          cpus: '0.05'
          memory: 15M
    healthcheck:
      test: ["CMD", "pgrep", "python"]
      interval: 10s
      timeout: 1s
      retries: 2